#!/bin/sh

# Setup ========================================================================

# Creates a goinfre directory (to run apps and files without permision).
if [ ! -e "$HOME/goinfre" ] ; then
  mkdir /goinfre/$(whoami)
fi

# Checks if brew is installed, then it downloads and install brew.
if [ ! -d "$HOME/goinfre/brew/bin" ] ; then
  git clone https://github.com/Homebrew/homebrew.git ~/goinfre/brew
  brew update
fi

# iterm might take a while to start because there can be some log reports
# in the Logs directory of the local system.
rm -rf ~/Library/Logs/DiagnosticReports/

# ======================================================================== Setup
