#!/bin/sh

# Aliases ======================================================================

alias open="xdg-open"
alias refresh='browser-sync start --server --files "*/*"'

# ====================================================================== Aliases
