#!/bin/sh

# Aliases ======================================================================

alias open="xdg-open &> /dev/null"
alias refresh='browser-sync start --server --files "*/*"'

# ====================================================================== Aliases
