#!/bin/sh

# Aliases ======================================================================

alias atom='open -a Atom.app'
alias subl='open -a Sublime\ Text.app'
alias chrome='open -a Chrome.app'
alias firefox='open -a Firefox.app'
alias brew="$HOME/goinfre/brew/bin/./brew"
alias compile='python ~/.bin/compile.py'
alias refresh='browser-sync start --server --files "*/*"'
alias vs-code='open -a ~/Applications/Visual\ Studio\ Code.app'
alias vscode='vs-code'
alias dropplet='open -a /Applications/Utilities/Digital\ Color\ Meter.app/'
alias skype='open -a ~/Applications/Skype.app/'

# ====================================================================== Aliases
